apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport-service
spec:
  type: NodePort
  selector:
    app: backend-service
  ports:
    - name: backend-service
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080