apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport-service
spec:
  type: NodePort
  selector:
    app: frontend-service
  ports:
    - name: frontend-service
      protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 30200
